# Local Development Testing Script
Write-Host "=== Solar Monitoring Local Development ==="
Write-Host ""
Write-Host "OPEN THREE SEPARATE POWERSHELL WINDOWS:"
Write-Host ""
Write-Host "WINDOW 1 - Azure Functions:"
Write-Host "cd $env:USERPROFILE\Desktop\solarmonitoringapp\api"
Write-Host "npm install"
Write-Host "func start --port 7071"
Write-Host ""
Write-Host "WINDOW 2 - Static Web Apps:"
Write-Host "cd $env:USERPROFILE\Desktop\solarmonitoringapp"
Write-Host "swa start . --api-devserver-url "http://localhost:7071" --port 4286"
Write-Host ""
Write-Host "WINDOW 3 - Testing:"
Write-Host "cd $env:USERPROFILE\Desktop\solarmonitoringapp"
Write-Host "Start-Process "http://localhost:4286/meter.html""
Write-Host ""
Write-Host "TESTING ENDPOINTS:"
Write-Host "http://localhost:4286/meter.html - Main Dashboard"
Write-Host "http://localhost:7071/api/GetPlantDirectory - API Test"
Write-Host "http://localhost:7071/api/GetPremier300MeterAll?top=5 - Meter Data"
Write-Host ""
Write-Host "PRODUCTION DEPLOYMENT:"
Write-Host "git add ."
Write-Host "git commit -m "Your message""
Write-Host "git push origin main"
Write-Host ""
Write-Host "PRODUCTION URL: https://gray-desert-0663e5d00.2.azurestaticapps.net/meter.html"
