name: Azure Static Web Apps CI/CD
concurrency:
  group: swa-$\{{ github.ref }}
  cancel-in-progress: true


on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - uses: actions/checkout@v4

      - name: Build & Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "."
          api_location: "api"
          output_location: "."
          skip_app_build: true   # static assets already present
          skip_api_build: false  # we need node_modules for Functions

